### PR TITLE
Adjusted FAQ to explain why we have ads

### PR DESCRIPTION
**Pull request by alex-shen1**
## Status

- Done

## GitHub Issues addressed

- This PR closes

## What I did

-

## Screenshots

- Before
image

- After
image

## Tests

- A brief explanation of tests done/written or how reviewers can test your work

## Questions/Discussions/Notes

-

## Merging the PR

- Who should merge this PR?
  - [] I will merge it myself
  - [x] The last reviewer to approve can merge it
- Should the commit history be preserved in the base branch, or is it okay to combine all of them into a single commit ("squash-merge")?
  - [] preserve the history
  - [x] squash-merge

### CODE REVIEW

**Comment by julesfll** [comment]
Does the "this has been a subject of confusion in the past" sound too passive agressive

**Comment by alex-shen1** [comment]
I personally don't think so? I don't remember who wrote the original text, but it was probably me so I might be biased.

**Comment by julesfll** [comment]
Oh also might want to change the wording to "make a profit from the site" since we technically do make money from the site

**Comment by j-alicia-long** [comment]
^Agree w/ the change in wording, @alex-shen1 once you make the edits I can approve!

**Comment by j-alicia-long** [comment]
Changed it to this:
`"No, our site is entirely a student volunteer effort. To be clear: We have never and will never profit from the site. While we do run ads to cover part of our server costs, they are only a small fraction of our budget and we don't pocket any of it. We get most of our funding from university grants, sponsors, and donations from users like you!"`

**Review by j-alicia-long — APPROVED** [review]

**Pull request merged**
