### PR TITLE
Review drive spring 2023

### PR DESCRIPTION
**Pull request by ajnye**
## GitHub Issues addressed

- This PR closes nothing.

## What I did

- Added a banner for the spring review drive, as well as updated the roster and executive page.

## Screenshots

- Before
Screen Shot 2023-04-24 at 1 12 13 PM
Screen Shot 2023-04-24 at 1 12 18 PM
- After
Screen Shot 2023-04-24 at 1 14 47 PM
Screen Shot 2023-04-24 at 1 14 57 PM
Screen Shot 2023-04-24 at 1 29 39 PM

## Testing

- A brief explanation of tests done/written or how reviewers can test your work
- Check the about page and the landing page. Make sure all the pictures work and no information is outdated.

## Questions/Discussions/Notes

-

### CODE REVIEW

**Comment by obs4qqf** [comment]
Thanks for adding the review drive banner and updating the members list! For the exec board, I think Jasmine ended up filling in the secretary position, so we'll need to add her info there. Also, I added a comment for the review drive banner that we might wanna change for clarity

**Comment by ajnye** [comment]
> Thanks for adding the review drive banner and updating the members list! The pictures on the about page and landing page look good and all the info looks like it was updated. For the exec board, I think Jasmine ended up filling in the secretary position, so we'll need to add her info there. Also, I added a comment for the review drive banner that we might wanna change for clarity

Fixed the exec positions. Where is the comment for the review drive banner?

**Comment by obs4qqf** [comment]
It should be under Files Changed, but I mostly said that we should change 2022 to 2023 in the banner and possibly remove the message about email login since I think that was for the last review drive

**Comment by ajnye** [comment]
> 

Fixed the year change, thanks for the catch!

**Review by obs4qqf — APPROVED** [review]

**Pull request merged**
