### PR TITLE
add about and img for Rui - dev team

### PR DESCRIPTION
**Pull request by RuiyuZhang69**
## Screenshots

- After
IMG_1166

## Questions/Discussions/Notes

-

### CODE REVIEW

**Comment by ajnye** [comment]
You might need to redo your branch - looks like you somehow reverted some dev changes in your commits so this branch is attempting to change the code of the dev branch that you didn't edit. I'd recommend making a new branch/PR and moving over the changes you specifically made (to the json and for the picture).

**Comment by ajnye** [comment]
Also, your picture isn't 800x800 (looks like it's 800x657?), although it's quite close, you should probably resize it.

**Comment by barrett-ruth** [comment]
@RuiyuZhang69

**Review by barrett-ruth — APPROVED** [review]
lgtm

**Pull request merged**
