### PR TITLE
Add alum page

### PR DESCRIPTION
**Pull request by j-alicia-long**
Added alums page, can be navigated to w/ tabs on About page

### CODE REVIEW

**Comment by j-alicia-long** [comment]
only concern I have is where to put the json files with the team/alum info - currently I have it in tcf_website/views/

**Comment by brian-yu** [comment]
> only concern I have is where to put the json files with the team/alum info - currently I have it in tcf_website/views/

I think that's fine for now!

**Comment by bradknaysi** [comment]
quick approval for a PR with 63 file changes 🤔

**Comment by brian-yu** [comment]
> quick approval for a PR with 63 file changes 🤔
In my defense, most of those are alum images!

**Pull request merged**
