### PR TITLE
Added Kingsley Kim image and name to the about team page

### PR DESCRIPTION
**Pull request by kingsleykimm**
## GitHub Issues addressed

- This PR closes

## What I did

- I added my name and image to the about team page.

## Screenshots

- Before
- After

## Testing

- A brief explanation of tests done/written or how reviewers can test your work

## Questions/Discussions/Notes

-

### CODE REVIEW

**Review by Ann924 — CHANGES_REQUESTED** [review]
Hey Kingsley, the changes look good! This is definitely a nitpick, but could you perhaps select another photo or edit your photo to extend the left and right borders of the image without using black space?

**Comment by kingsleykimm** [comment]
Sure! I'll have it updated in the next few days

**Review by Ann924 — CHANGES_REQUESTED** [review]
Nice photo, Kingsley! Could you edit it to be 800x800 pixels? I believe it is currently 3024x3024 pixels.

**Review by Ann924 — APPROVED** [review]
Nice! You can go ahead and merge your branch into dev whenever you're ready.

**Comment by Ann924** [comment]
Yup, you're right. I just merged in Zohaib's, which caused a merge conflict with your branch. Could you please resolve the merge conflict on your end? Let me know when you're ready and I'll close this PR for you.

**Review by Ann924 — CHANGES_REQUESTED** [review]
ENG_Arthur_Wu.jpg and ENG_Zohaib_Khalid.jpg were not merged into tcf_website/static/about/team-pfps, which causes some errors on display.

image

**Comment by kingsleykimm** [comment]
Ok hopefully this commit works, I don't think there should be any merge conflicts unless dev changes again

**Comment by barrett-ruth** [comment]
@Ann924 should be good I think

**Review by Ann924 — APPROVED** [review]

**Pull request merged**
