### PR TITLE
726 UI fix center icons in footer on homepage

### LINKED ISSUE #726: UI Fix: Center icons in footer on homepage
The icons for TCF socials (Discord, Facebook, Insta, Twitter) in the footer of the homepage are not centered vertically in the footer. See in the screenshot: 
image

### PR DESCRIPTION
**Pull request by artiehumphreys**
## GitHub Issues addressed

- Fixes #726 

## What I did

- Changed alignment of social media icons so that they are centered on the footer

## Screenshots

- Before:
image
- After:
Screenshot 2023-10-30 at 10 00 39 PM

## Testing

- More testing might be required

## Questions/Discussions/Notes

- It works when you shrink the media size, but more testing might be required

### CODE REVIEW

**Comment by barrett-ruth** [comment]
@artiehumphreys did you see my review?

**Comment by artiehumphreys** [comment]
> @artiehumphreys did you see my review?

No, was it on one of the previous commits?

**Comment by barrett-ruth** [comment]
I guess my reviews just don't show up, idk why. Anyways:

image

**Comment by barrett-ruth** [comment]
@artiehumphreys sorry to ask this but there's just a bunch of diffs in the commit if you go to "files changed" - I can't parse if all the code is the same if its reformatted there.

We definitely need to format the entire project code so this isn't an issue - I'll get on that tomorrow.

In the meantime, can you undo the file formatting diffs and only change the necessary lines? Sorry to ask again

**Comment by artiehumphreys** [comment]
> @artiehumphreys sorry to ask this but there's just a bunch of diffs in the commit if you go to "files changed" - I can't parse if all the code is the same if its reformatted there.
> 
> We definitely need to format the entire project code so this isn't an issue - I'll get on that tomorrow.
> 
> In the meantime, can you undo the file formatting diffs and only change the necessary lines? Sorry to ask again

@barrett-ruth I saw that and that's completely my fault I formatted the document in VSCode and that messed up everything up. I tried resetting to older commits and reverting the file within VSCode to no avail. I'll see what I can do tomorrow.

**Review by barrett-ruth — APPROVED** [review]
lgtm

**Pull request merged**
