### PR TITLE
Hot fix for bugs after merging #153

### LINKED ISSUE #178: All JS functions broke after #153 was merged
image

### PR DESCRIPTION
**Pull request by Bartleby2718**
# What I did
I could fix `Uncaught SyntaxError: Unexpected token 'export'` by adding a few `type="module"`s, but somehow the functions needed to be defined beforehand. During the debugging process, I discovered that [using the `onclick` attribute is not a good practice](https://stackoverflow.com/questions/12627443/jquery-click-vs-onclick), so I replaced all of them with `addEventListener`s.

## Issues addressed
Fix #178 (hopefully?)

# Screenshots
This is the screenshot after I've clicked `Rating`, `Difficulty`, `GPA`, `Number`, in that order.
image

# Note
Please squash-merge this one!

### CODE REVIEW

**Review by j-alicia-long — APPROVED** [review]
Good catch! Thanks for fixing this :)

**Comment by Bartleby2718** [comment]
@j-alicia-long Are PRs merged only during weekly meetings? I thought this bug would affect everyone branching off from `dev`, which is why I spent the past few hours working on this.

**Comment by alex-shen1** [comment]
Doesn't seem to work for me? I just click on the sort buttons and nothing happens...could be a local issue w/ my build but I'm not sure why. The "sorted category" bold (number, rating, etc.) does change based on what I've clicked, which is a step up from the current status of `dev`, but the elements don't actually sort.

Also, PRs can get merged at any time really, but typically the actual merge is left to the creator of the PR after reviewers approve.

**Comment by alex-shen1** [comment]
Whoops, it just turns out that we don't have many reviews for the Art department so sorting doesn't work because we don't have data :/

**Comment by j-alicia-long** [comment]
> @j-alicia-long Are PRs merged only during weekly meetings? I thought this bug would affect everyone branching off from `dev`, which is why I spent the past few hours working on this.

Oh no, thanks for addressing this quickly! I was just waiting for a second reviewer in case they caught anything I missed. Merging it now~

**Comment by Bartleby2718** [comment]
@j-alicia-long Thanks for the review! I just wanted to make sure I clean up the mess I made ASAP...

**Pull request merged**
