### PR TITLE
Fix #361 404 Not found when clicking privacy policy

### LINKED ISSUE #360: 404 Not found when clicking privacy policy
## Describe the bug
On the homepage FAQ, there is a link to the site privacy policy underneath "How do you protect reviewers' privacy?"

Clicking this link leads to a 404.

## To Reproduce
1. Go to [theCourseForum homepage](https://www.thecourseforum.com/)
2. Scroll down to FAQs
3. Click the "Privacy Policy" link
4. Observe the 404

## Expected behavior
I expect to see the site's privacy policy.

## Screenshots
image

## Your Environment:
 - OS: Mac OSX
 - Browser: Brave (uses Chromium)

## Additional context
Using Chrome devtools, it looks like maybe the issue lies in the homepage template. 
image
(Notice the `href` set to some unevaluated template logic)

### LINKED ISSUE #361: Get Django code coverage in precommit
**Is your feature request related to a problem? Please describe.**
PR #344 shows code coverage when the workflow is run, but we can't figure it out locally.

**Describe the solution you'd like**
@alex-shen1 suggested that it would be nice to add it to `precommit`. It has the extra benefit of removing a hard-coded command (`echo coverage >> requirements.txt`) from the workflow YAML file.

**Describe alternatives you've considered**
We can keep the status quo?

**Additional context**
@alex-shen1 brought this up [here](https://github.com/thecourseforum/theCourseForum2/pull/344#discussion_r565065295).

### PR DESCRIPTION
**Pull request by Bartleby2718**
## Status
- Done

## GitHub Issues addressed (`#IssueNumber`)
- This PR closes #360

## What I did
- Rendered the content of the `_faqs.json` earlier
- Refactored to remove unnecessary JS code

## Screenshots
- Before
image
- After
image

## Tests
1. Go to http://localhost:8000/
2. Expand `How do you protect reviewers' privacy?`
3. Click the hyperlink `Privacy Policy`

## Questions/Discussions/Notes
- I had to move the location of `_faqs.json` to keep the code clean.

## Merging the PR
- Who should merge this PR?
  - [ ] I will merge it myself
  - [x] The last reviewer to approve can merge it
    - Should the commit history be preserved in the base branch, or is it okay to combine all of them into a single commit ("squash-merge")?
    - [ ] preserve the history
    - [x] squash-merge

### CODE REVIEW

**Review by joek13 — APPROVED** [review]
I'm able to reproduce the fix on my machine—everything looks good so far, nice work thinking to render the JSON twice.

**Review by alex-shen1 — APPROVED** [review]
Nice job! I knew there had to be a better way to do the FAQ section lol

I am a little confused about the name of the branch/PR though....the privacy policy doesn't seem to be broken on prod anyways, and the changes don't seem to have anything to do with it?

**Comment by alex-shen1** [comment]
In any case, I'm just going to go ahead and merge.

**Comment by Bartleby2718** [comment]
Funny how I wrote #361 instead of #360 in the commit message smh...

**Comment by Bartleby2718** [comment]
@alex-shen1 `/privacy` is not broken, but the link in the FAQs is?
image

**Comment by alex-shen1** [comment]
Ah, I overlooked the issue. Welp, this is a lesson in actually reading the description. Whoops!

**Pull request merged**
