### PR TITLE
configured django-silk

### PR DESCRIPTION
**Pull request by j-alicia-long**
# What I did
Installed [django-silk](https://github.com/jazzband/django-silk) for performance profiling

## Issues addressed
#78 is resolved. Originally rolled it into a separate issue (#11 ) but decided to reopen since we're still addressing that.

# Screenshots
Created new url at http://localhost:8000/silk/. Can track load time for http requests and db queries as shown here: 
image

### CODE REVIEW

**Review by Bartleby2718 — COMMENTED** [review]
So are we allowing end users to access our performance data for all deployments (i.e. including the production website)? In terms of performance, installing one more package or running one more app isn't a big deal, but not sure if you'd want to share the data.

**Comment by alex-shen1** [comment]
Yeah, seems like something we should remove at some point? Might be nice to have it stick around in dev branch, though; not sure if that makes it annoying to merge dev into master going forward because we have to specifically block one commit from going into prod each time we update master

**Review by alex-shen1 — COMMENTED** [review]
As a side note, is there any particular rationale for the ordering of the apps/middlewares + if there isn't, is it worth having an ordering process?

**Comment by Bartleby2718** [comment]
@alex-shen1 I was thinking of adding an `if` statement in `tcf_core/urls.py` so that the endpoint is not added in the production environment.

**Comment by j-alicia-long** [comment]
> As a side note, is there any particular rationale for the ordering of the apps/middlewares + if there isn't, is it worth having an ordering process?

Yes, the ordering does matter to an extent, see below:
image
This is from the [django-silk docs](https://github.com/jazzband/django-silk) btw

**Comment by j-alicia-long** [comment]
> @alex-shen1 I was thinking of adding an `if` statement in `tcf_core/urls.py` so that the endpoint is not added in the production environment.

Good idea! I will do that.

**Comment by alex-shen1** [comment]
Re: keeping metrics private — if the tCF repo remains public, can't anyone just clone the repo and run it themselves to find out all this information? Pretty sure private repos cost money though so not sure what the solution is there

**Comment by j-alicia-long** [comment]
> Re: keeping metrics private — if the tCF repo remains public, can't anyone just clone the repo and run it themselves to find out all this information? Pretty sure private repos cost money though so not sure what the solution is there

Actually, according to GitHub's current pricing plan (https://github.com/pricing) we now have unlimited private repos are for free accounts! Will make the change to private this week :)

**Review by alex-shen1 — APPROVED** [review]
Works on my machine too.

**Review by Bartleby2718 — APPROVED** [review]

**Pull request merged**
