### PR TITLE
tCF Accessibility Improvements - Proper Contrast Ratios

### PR DESCRIPTION
**Pull request by wkaisertexas**
Howdy howdy howdy. My name is William Kaiser, and I am a newer member here at *theCourseForum*. One thing that was bugging me was the lack of adequate contrast ratios(>4) in the user interface, something which the [W3C](https://www.w3.org/WAI/standards-guidelines/wcag/) recommends. To calculate proper ratios for different size text, I used [web aim's calculator](https://webaim.org/resources/contrastchecker/) which is handy. 

## GitHub Issues addressed

#681 Proper Contrast Ratios

## What I did

Two main things:
- No longer using `var(--background-color)` for text as this made contrast ratios really hard to hit. Instead, just using `white` text
- Removing the decreased brightness `brightness 85%` which was making the sidebar look off
- Removed `opacity(0.75)` from the home screen because the central log and the header logo being slightly different colors was a little strange. 

## Screenshots

- Before
Screenshot 2023-10-10 at 9 39 28 PM
Screenshot 2023-10-10 at 9 35 27 PM

- After

Screenshot 2023-10-10 at 9 37 27 PM
Screenshot 2023-10-10 at 9 36 34 PM

## Testing

- Only CSS modified. Low risks of externalities present. Furthermore, the rest of the site was examined for induced style glitches of which there were none found.

## Questions/Discussions/Notes

Note: this is an open pull request because there will no doubt be similar, small tweaks to the user interface which make it arguable more readable.

### CODE REVIEW

**Review by barrett-ruth — COMMENTED** [review]
LGTM. @ajnye are you ok with these color changes

**Comment by wkaisertexas** [comment]
??? what is the status with this?

**Comment by ajnye** [comment]
I'll remind the UI UX Designers to take a look at it.

**Comment by ajnye** [comment]
It's been approved by Jasmine, I'll just make sure it runs with no issue and then merge it.

**Review by ajnye — APPROVED** [review]
Looks good

**Pull request merged**
